kind: Cluster
metadata:
  name: rauto-infraprovisioner-eks-76423
  project: defaultproject
spec:
  blueprint: default
  cloudprovider: rauto-cloudprovider-76423
  type: eks
---
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
metadata:
  name: rauto-infraprovisioner-eks-76423
  region: us-west-1
  version: "1.20"
nodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 1
  iam:
    withAddonPolicies:
      albIngress: true
      autoScaler: true
      efs: true
      externalDNS: true
      imageBuilder: true
  instanceType: t3.xlarge
  maxSize: 1
  minSize: 1
  name: rauto-infraprovisioner-eks-76423-ng
  volumeSize: 80
  volumeType: gp3
vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  nat:
    gateway: Single